# Change these first
owner: MolefiEdward
repo: upptime-monitor

sites:
  - name: My App
    url: https://upptime-nu.vercel.app/
    method: GET
    expect:
      statusCode: 200

status-website:
  baseUrl: /upptime-monitor
  name: "My App Status"
  logoUrl: https://example.com/logo.png  # Optional but recommended
  introTitle: "**Upptime** is the open-source uptime monitor and status page"
  introMessage: This is a sample status page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Add this section
workflow-schedule:
  graphs: "0 0 * * *"        # Daily at midnight
  responseTime: "0 23 * * *"  # Daily at 11 PM
  staticSite: "0 1 * * *"     # Daily at 1 AM
  summary: "0 0 * * *"        # Daily at midnight
  updateTemplate: "0 0 * * *" # Daily at midnight
  updates: "0 3 * * *"        # Daily at 3 AM
  uptime: "*/5 * * * *"       # Every 5 minutes

# Notifications (optional)
notifications:
  - type: email
    to:
      - molefiedwardmofokeng@gmail.com
